config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "events#index"
  resources :events
  resources :users, only: [:index]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true

    has_many :user_to_events
    has_many :users, through: :user_to_events
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true

    has_many :user_to_events
    has_many :events, through: :user_to_events

    after_create :send_greetings

    def send_greetings
        UserMailer.welcome_email(self).deliver_now
    end
end

app/models/user_to_event.rb
class UserToEvent < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_admin!, only: [:create, :edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.paginate(page: params[:page], per_page: 10)
  end

  # GET /events/:id
  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "Your event has been successfully saved"
      redirect_to event_path(@event)
    else
      flash[:alert] = "An error has occurred"
      render 'new'
    end
  end

  def edit
  end

  # DELETE
  def destroy
    if @event.destroy
      flash[:notice] = "Event correctly deleted"
      redirect_to events_path
    else
      flash[:alert] = "An error has occurred"
      redirect_back(fallback_location: root_path)
    end
  end

  # PUT /events/update
  def update
    if @event.update(event_params)
      flash[:notice] = "Event correctly modified"
      redirect_to event_path(@event)
    else
      flash[:alert] = "An error has occurred"
      render 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :address, :description)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for event do |f| %>
    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
        <%= f.label :address %><br>
        <%= f.text_field :address %><br>
        <%= f.label :description %><br>
        <%= f.text_field :description %><br>
        <%= f.submit %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>

<ul>
<% @events.each do |event| %>
    <li><%= link_to event.name, event_path(event) %></li>
<% end %>
</ul>

<% if admin_signed_in? %>
    <%= link_to "New", new_event_path, class: "btn btn-info" %>
<% end %>

<div class="apple_pagination">
    <%= will_paginate @events %>
</div>

app/views/events/new.html.erb
<h1>New</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<h2>Description</h2>

<p><%= @event.description %></p>

<h2>Address</h2>

<p><%= @event.address %></p>

<h2>Users</h2>

<ul>
<% @event.users.each do |user| %>
    <li><%= user.first_name %></li>
<% end %>
</ul>

<% if admin_signed_in? %>
    <%= link_to "Edit", edit_event_path(@event), class: "btn btn-info" %>
    <%= link_to "Delete", event_path(@event), data: { confirm: "Are you sure ?" }, class: "btn btn-danger", method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEventApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'will_paginate_custom', media: 'all' %>
    <!-- This refers to app/javascript/stylesheets/application.scss-->
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Events", events_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_admin_session_path, :method => :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">
                <%= link_to "Log in", new_admin_session_path, class: "nav-link" %>
              </a>
              <a class="dropdown-item" href="#">
                <%= link_to "Sign up", new_admin_registration_path, class: "nav-link" %>
              </a>
            </div>
          </li>
        <% end %>
      </ul>
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
<% @users.each do |user| %>
    <li><%= user.first_name %> <%= user.last_name %></li>
<% end %>
</ul>

<div class="apple_pagination">
    <%= will_paginate @users %>
</div>